"""Add SMTP defaults to User model

Revision ID: fcb21051fa2d
Revises: 5c5aee7c5184
Create Date: 2025-07-05 00:40:00.251063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcb21051fa2d'
down_revision = '5c5aee7c5184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('smtp_host',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('smtp_port',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('smtp_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('smtp_password_encrypted',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('smtp_password_encrypted',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('smtp_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('smtp_port',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('smtp_host',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
